import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { sendEmail, emailTemplate, emailConfigured } from '@/lib/alerts/channels'
import { escapeHtml } from '@/lib/alerts/deliver'
import { generateBriefing } from '@/lib/ai/briefing'
import { buildSnapshot } from '@/lib/ai/snapshot'
import { withCronErrorAlert } from '@/lib/monitoring'

export const dynamic = 'force-dynamic'
export const maxDuration = 60

// Daily AI monitor: reads the books, Claude writes a prioritized briefing,
// delivered to founder + accountant. Triggered by Vercel Cron.
export async function GET(request: Request) {
  return withCronErrorAlert('ai-briefing', () => run(request))
}
async function run(request: Request) {
  const secret = process.env.CRON_SECRET
  if (!secret || request.headers.get('authorization') !== `Bearer ${secret}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  if (!emailConfigured()) {
    return NextResponse.json({ ok: true, skipped: 'no alert channel configured' })
  }

  const admin = createAdminClient()
  if (!admin) return NextResponse.json({ error: 'SUPABASE_SERVICE_ROLE_KEY not set' }, { status: 500 })

  const today = new Date()

  // Snapshot (shared with the Founder Brief) + the alert recipients.
  const [snapshot, recipients] = await Promise.all([
    buildSnapshot(admin),
    admin.from('profiles').select('email, full_name, email_alerts, whatsapp_alerts, whatsapp_number').in('role', ['founder', 'accountant']).eq('is_active', true),
  ])

  const briefing = await generateBriefing(snapshot)

  // ── Infrastructure rollup from the watchdog (last 24h of agent_incidents) ──
  const since24 = new Date(today.getTime() - 24 * 86400000).toISOString()
  const { data: incidents } = await admin
    .from('agent_incidents')
    .select('service, description, status, severity, created_at')
    .gte('created_at', since24)
    .order('created_at', { ascending: false })
  const inc = incidents ?? []
  const autoResolved = inc.filter(i => i.status === 'resolved').length
  const stillOpen = inc.filter(i => ['open', 'escalated', 'acknowledged'].includes(i.status as string))
  const infraHtml =
    `<p style="margin:20px 0 6px;font-weight:600;border-top:1px solid #e4e4e7;padding-top:14px;">Infrastructure (last 24h)</p>` +
    (stillOpen.length
      ? `<ul style="margin:0;padding-left:18px;line-height:1.7;">` +
        stillOpen.map(i => `<li><strong>${escapeHtml(String(i.service))}:</strong> ${escapeHtml(String(i.description ?? ''))} <em>(${escapeHtml(String(i.status))})</em></li>`).join('') +
        `</ul>`
      : `<p style="margin:0;">✅ All systems healthy.</p>`) +
    `<p style="margin:6px 0 0;font-size:12px;color:#71717a;">${autoResolved} incident${autoResolved === 1 ? '' : 's'} auto-resolved · ${stillOpen.length} still open.</p>`

  const dateStr = today.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
  const html = emailTemplate(
    `Morning Briefing — ${dateStr}`,
    `<p style="margin:0 0 12px;font-weight:600;">${escapeHtml(briefing.headline)}</p>` +
    (briefing.itemsHtml ? `<ul style="margin:0;padding-left:18px;line-height:1.7;">${briefing.itemsHtml}</ul>` : '<p style="margin:0;">Nothing needs attention today.</p>') +
    infraHtml +
    `<p style="margin:16px 0 0;font-size:11px;color:#a1a1aa;">Generated by your OPM Flash AI monitor. Figures are read-only — it never changes anything.</p>`
  )
  // Email-only: this AI briefing is newsletter-style content that WhatsApp's
  // Business Platform treats as non-utility and won't approve as a template.
  const list = recipients.data ?? []
  let sent = 0
  for (let i = 0; i < list.length; i++) {
    const r = list[i]
    if (r.email_alerts && r.email) {
      if (await sendEmail(r.email, `OPM Flash — Morning Briefing (${dateStr})`, html)) sent++
    }
    if (i < list.length - 1) await new Promise(res => setTimeout(res, 600))
  }

  return NextResponse.json({ ok: true, recipients: list.length, sent, headline: briefing.headline, urgent: briefing.hasUrgent })
}
