import Anthropic from '@anthropic-ai/sdk'

// Turns a week's financial snapshot into a plain-English management report.
// Uses Claude when configured; falls back to a deterministic summary.

const inr = (n: number) => `₹${Math.round(n).toLocaleString('en-IN')}`

export interface ProjectWeekly { name: string; received: number; spent: number }

export interface WeeklySnapshot {
  weekLabel: string            // e.g. "9–15 Jun 2026"
  available: number            // cash + bank now
  inflow: number               // income received this week
  outflow: number              // payments paid this week
  collectedYtdHint?: string
  receivableOutstanding: number
  liabilitiesOutstanding: number
  pendingApprovals: { count: number; total: number }
  monthlyPayroll: number
  loanMonthlyInterest: number
  topProjects: ProjectWeekly[] // by activity this week
  attention: string[]          // pre-computed flags (overdue dues, low cash, contract dates)
}

export interface WeeklyReport {
  headline: string
  bodyHtml: string   // inner HTML for the email body
}

function snapshotToText(s: WeeklySnapshot): string {
  const net = s.inflow - s.outflow
  const lines = [
    `Week: ${s.weekLabel}`,
    `Available now (cash + bank): ${inr(s.available)}`,
    `This week — collected: ${inr(s.inflow)}; paid out: ${inr(s.outflow)}; net: ${inr(net)}`,
    `Outstanding receivables: ${inr(s.receivableOutstanding)}`,
    `Outstanding liabilities: ${inr(s.liabilitiesOutstanding)}`,
    `Pending approvals: ${s.pendingApprovals.count} totalling ${inr(s.pendingApprovals.total)}`,
    `Recurring monthly payroll: ${inr(s.monthlyPayroll)}; monthly loan interest: ${inr(s.loanMonthlyInterest)}`,
  ]
  s.topProjects.forEach(p => lines.push(`  - project ${p.name}: collected ${inr(p.received)}, spent ${inr(p.spent)} this week`))
  s.attention.forEach(a => lines.push(`  - attention: ${a}`))
  return lines.join('\n')
}

const SYSTEM = `You are the management accountant for OPM Cinemas, an Indian film-production company (amounts in ₹). Each week you write the founder a concise management report from the week's numbers. Cover: cash position & runway feel, collections vs spending, per-project activity, and what needs attention next week. Be specific with names and ₹ amounts, plain and direct, no filler or greetings. It's a status report a busy founder reads in 30 seconds.`

const SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    headline: { type: 'string', description: 'One-line state of the business this week (≤ 90 chars)' },
    sections: {
      type: 'array',
      description: '3–5 short sections',
      items: {
        type: 'object', additionalProperties: false,
        properties: {
          title: { type: 'string', description: 'Section label, e.g. "Cash & runway", "Collections", "Per project", "Next week".' },
          points: { type: 'array', items: { type: 'string' }, description: '1–4 specific bullet points with names and ₹.' },
        },
        required: ['title', 'points'],
      },
    },
  },
  required: ['headline', 'sections'],
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function renderHtml(headline: string, sections: { title: string; points: string[] }[]): string {
  const blocks = sections.map(sec =>
    `<p style="margin:14px 0 4px;font-weight:600;color:#18181b;">${esc(sec.title)}</p>` +
    `<ul style="margin:0;padding-left:18px;line-height:1.7;">${sec.points.map(p => `<li>${esc(p)}</li>`).join('')}</ul>`
  ).join('')
  return `<p style="margin:0 0 6px;font-weight:600;">${esc(headline)}</p>${blocks}` +
    `<p style="margin:16px 0 0;font-size:11px;color:#a1a1aa;">Generated by your OPM Office AI — read-only weekly summary.</p>`
}

function deterministic(s: WeeklySnapshot): WeeklyReport {
  const net = s.inflow - s.outflow
  const sections: { title: string; points: string[] }[] = [
    { title: 'Cash & runway', points: [
      `Available now: ${inr(s.available)} (cash + bank).`,
      `Fixed monthly load: payroll ${inr(s.monthlyPayroll)}${s.loanMonthlyInterest ? ` + loan interest ${inr(s.loanMonthlyInterest)}` : ''}.`,
    ] },
    { title: 'This week', points: [
      `Collected ${inr(s.inflow)}, paid out ${inr(s.outflow)} — net ${inr(net)}.`,
      `Receivables outstanding: ${inr(s.receivableOutstanding)}; liabilities outstanding: ${inr(s.liabilitiesOutstanding)}.`,
      `${s.pendingApprovals.count} payment${s.pendingApprovals.count === 1 ? '' : 's'} awaiting approval (${inr(s.pendingApprovals.total)}).`,
    ] },
  ]
  if (s.topProjects.length) sections.push({ title: 'Per project', points: s.topProjects.map(p => `${p.name}: +${inr(p.received)} / -${inr(p.spent)} this week.`) })
  if (s.attention.length) sections.push({ title: 'Needs attention', points: s.attention })
  return { headline: net >= 0 ? `Net positive week: ${inr(net)}` : `Net outflow this week: ${inr(-net)}`, bodyHtml: renderHtml('Weekly summary', sections) }
}

export async function generateWeeklyReport(snapshot: WeeklySnapshot): Promise<WeeklyReport> {
  if (!process.env.ANTHROPIC_API_KEY) return deterministic(snapshot)
  try {
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
    const response = await client.messages.create({
      model: 'claude-opus-4-8',
      max_tokens: 2000,
      system: SYSTEM,
      output_config: { format: { type: 'json_schema', schema: SCHEMA } },
      messages: [{ role: 'user', content: `This week's numbers:\n\n${snapshotToText(snapshot)}\n\nWrite the weekly report.` }],
    })
    const block = response.content.find(b => b.type === 'text')
    if (!block || block.type !== 'text') return deterministic(snapshot)
    const parsed = JSON.parse(block.text) as { headline: string; sections: { title: string; points: string[] }[] }
    const sections = (parsed.sections ?? []).filter(s => s?.title && Array.isArray(s.points))
    if (!sections.length) return deterministic(snapshot)
    return { headline: parsed.headline || 'Weekly summary', bodyHtml: renderHtml(parsed.headline || 'Weekly summary', sections) }
  } catch {
    return deterministic(snapshot)
  }
}
